import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { parse, compileScript, compileTemplate } from 'vue/compiler-sfc'
import { ManualEngine, PRESETS, frequency, validatePlans } from '../audio/manualEngine.js'
import { editPlans, midiBytes } from '../audio/midiEditing.js'
const note = { start_beat: 0, duration_beats: .5, midi_note: 72, velocity: 44, voice: 'melody', phrase: 0 }
const plans = () => ({ M1: { notes: [note, { ...note, voice: 'bass', midi_note: 48 }, { ...note, voice: 'pad' }] }, M2: { notes: [{ ...note, duration_beats: 1 }] }, M3: { notes: [] } })
class Param { constructor(value = 0) { this.value = value; this.calls = [] } setValueAtTime(v,t) { this.calls.push(['set',v,t]); this.value=v } linearRampToValueAtTime(v,t) { this.calls.push(['ramp',v,t]); this.value=v } cancelAndHoldAtTime(t) { this.calls.push(['hold',t]) } cancelScheduledValues(t) { this.calls.push(['cancel',t]) } }
class Node { constructor() { for (const key of ['gain','frequency','pan','Q','delayTime','threshold','knee','ratio','attack','release']) this[key] = new Param(); this.connections = [] } connect(node) { this.connections.push(node) } disconnect() {} start(t) { this.started=t } stop(t) { this.stopped=t } }
function harness(options = {}) { const context = { currentTime: 0, sampleRate:48000, state:'running', destination:{}, sources:[], oscillators:[], async resume(){}, async close(){this.closed=true}, async decodeAudioData(){return { duration:60 }} }; for (const method of ['createGain','createBiquadFilter','createDelay','createDynamicsCompressor','createStereoPanner']) context[method]=()=>new Node(); context.createBufferSource=()=>{const n=new Node();context.sources.push(n);return n}; context.createOscillator=()=>{const n=new Node();context.oscillators.push(n);return n}; const engine = new ManualEngine({ contextFactory:()=>context, fetcher:async()=>({ok:true,headers:{get:()=>null},arrayBuffer:async()=>new ArrayBuffer(8)}), ...options }); return {engine,context} }
test('workbench and audio utilities compile',()=>{const {descriptor}=parse(readFileSync(new URL('./MusicWorkbench.vue',import.meta.url),'utf8'));compileScript(descriptor,{id:'workbench'});assert.deepEqual(compileTemplate({source:descriptor.template.content,filename:'MusicWorkbench.vue',id:'workbench'}).errors,[]);assert.equal(frequency(69),440);assert.deepEqual(Object.keys(PRESETS),['M1','M2','M3'])})
test('MIDI edits validate and preserve Suno pad semantics',()=>{const edited=editPlans(plans(),{motif:'72 74 76 77',transpose:-12,durationScale:2});assert.equal(edited.M1.notes[0].midi_note,60);assert.equal(edited.M1.notes[0].duration_beats,1);assert.equal(edited.M1.notes.length,2);assert.equal(edited.M3.notes.length,0);assert.throws(()=>editPlans(plans(),{motif:'72 73 76 77'}),/动机/);assert.throws(()=>editPlans(plans(),{motif:'72 74'}),/动机/);assert.throws(()=>validatePlans({}),/不完整/);assert.deepEqual(midiBytes(edited.M1).slice(0,4),new Uint8Array([77,84,104,100]))})
test('synchronized sources and state requests use phrase boundaries',async()=>{const h=harness();await h.engine.start({padId:'a',textureId:'b',plans:plans()});try { assert.equal(h.context.sources.length,2);assert.equal(h.context.sources[0].started,h.context.sources[1].started);assert.equal(h.context.sources[0].loop,false);h.context.currentTime=.1;h.engine.tick();assert.equal(h.context.oscillators.length,2);h.engine.requestState('M3');h.context.currentTime=16.1;h.engine.tick();assert.equal(h.engine.active,'M1');h.context.currentTime=16.21;h.engine.tick();assert.equal(h.engine.active,'M3');assert.equal(h.context.sources.length,2);assert.ok(h.engine.exportLog().events.some(e=>e.type==='state-applied'&&e.state==='M3'))} finally {h.engine.stop()}assert.equal(h.context.closed,true)})
test('layer trims, output cap, cancellation and errors are safe',async()=>{const h=harness();await h.engine.start({padId:'a',plans:plans()});h.engine.setLayerLevel('melody',0);h.engine.setVolume(9);assert.equal(h.engine.volume,.4);h.engine.stop();assert.equal(h.engine.running,false);let resolve;const blocked=harness({fetcher:()=>new Promise(r=>{resolve=r})});const pending=blocked.engine.start({padId:'a',plans:plans()});await Promise.resolve();blocked.engine.stop();resolve({ok:true,headers:{get:()=>null},arrayBuffer:async()=>new ArrayBuffer(8)});await pending;assert.equal(blocked.context.sources.length,0);const failed=harness({fetcher:async()=>({ok:false})});await assert.rejects(failed.engine.start({padId:'a',plans:plans()}),/无法读取/);assert.equal(failed.context.closed,true)})
